######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 22 14:39:13 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BlackBox.h block.h DisplayZone.h GameBoard.h preview.h
SOURCES += BlackBox.cpp \
           Blocks.cpp \
           DisplayZone.cpp \
           GameBoard.cpp \
           main.cpp \
           preview.cpp
